language: node_js
deploy:
  provider: npm
  email: "chris@chrisdoingweb.com"
  api_key:
    secure: "ZSjqPLjWQp0GT7mFb15m9jZkv8Ljo4QKeBj1IdJJnM6wLgMzyXEX/+O8zRFi59xUWevJsfbx38bau8kkGoh+g+MUMa72e/sgl6KLu/8bszRa8+LVj/1jN4fGBbDi6qrqNTmP3oerlcMhHBGJX4euDNPDdmZ4LnTNgyecYBGl9sZmwY9nq7ujt/lBaF7tZeQkgdxkT3kEf6IYUNtZ+J24LmmkeARgGUE2d9y4P2en1yw2O/SYxqOjKpTJmDlLP65qVDtamSBtDHMZ6oWbllYp2iO5pSQXYssMECW/CDZuL4Jy+TlJij8diFxC9o1y59F16j0HsTIgi2Xaoe47ES/4ZLY/9Sml9rX9JfiJrKy+hLZ3Ce5JwKlrW7lknslxlGq/VrwKrzF4EH/MH/eHTJ9AdV6I33v6nZew2ieZ4re4kpOADrT9ZoetaVJEZ0JR86Avpup+RMRi1Ch5H2A0EW4xki7PFvzMSaPnOohEdwISJ85v/ZktoT0AaxqNAMCP8hUQTFTIwigRTgHk911NpUGzVbucqisG596TAa1WXJf11N0ep4yiyAWaMlzspxVcFu//SWKhw/n0iaxn3wQQyhlwAEbWzLa4khzuckoY7O0YvwRkNZUDI9Q8uZMS0GMEiiXF4CUT+x+nPiaQNU5RAOKLQn4LfWXyX6DHxEN4HRUdnXE="
